<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="img/favicon.ico">
        <title>Help</title>

        <!-- Bootstrap core CSS -->
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="css/index.css" rel="stylesheet">
    </head>

    <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">Smolka Dots</a>
            </div>
        </div>
    </nav>

    <div class="container" id="centerinfo">
        <div>
            <h2>Help Page</h2>
            <p>
                <h3>Managers</h3>

                <h4>A manager is able to:</h4>
                <ul>
                    <li>Add, Edit and Delete information for an employee</li>
                    <li>Obtain a sales report for a particular month</li>
                    <li>Produce a comprehensive listing of all items</li>
                    <li>Produce a list of sales by item name or by customer name</li>
                    <li>Produce a summary listing of revenue generated by a particular item, item type, or customer</li>
                    <li>Determine which customer representative generated most total revenue</li>
                    <li>Determine which customer generated most total revenue</li>
                    <li>Produce a Best-Sellers list of items</li>
                </ul>
                <br>
                <h3>Customer-Representatives</h3>

                <h4>A Customer Representative is able to:</h4>
                <ul>
                    <li>Record a sale</li>
                    <li>Add, Edit and Delete information for a customer</li>
                    <li>Produce customer mailing lists</li>
                    <li>Produce a list of item suggestions for a given customer (based on that customer's past purchases)</li>
                </ul>
                <br>
                <h3>Customers</h3>

                <h4>A Customer is able to:</h4>
                <ul>
                    <li>A bid history for each auction</li>
                    <li>A history of all current and past auctions a customer has taken part in</li>
                    <li>Items sold by a given seller and corresponding auction info</li>
                    <li>Items available of a particular type and corresponding auction info</li>
                    <li>Items available with a particular keyword or set of keywords in the item name, and corresponding auction info</li>
                    <li>Best-Seller list</li>
                    <li>Personalized item suggestion list</li>
                </ul>
            </p>
        </div>

        <button type="button" class="btn btn-default btn-primary" onclick="history.back();">
            <span class="glyphicon glyphicon-circle-arrow-left" aria-hidden="true"></span>&nbsp;Back
        </button>
    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
</body>
</html>
